import Head from "next/head";

import { choozes } from "../../data";
import { FaPlus } from "react-icons/fa";

export default function Home() {
  console.log(choozes);
  return (
    <>
      <Head>
        <title>Chooze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/** NAVIGATION */}
        <section className="navigation">
          <a href="/" className="navigation-logo">
            <h1>Chooze</h1>
          </a>
          <FaPlus className="navigation-edit"/>
        </section>
      </main>
    </>
  );
}
