import Head from "next/head";
import { FaPlus, FaQuestion, FaAngleRight, FaTimes} from "react-icons/fa";
import { useState } from "react";

export async function getStaticProps() {
  try {
    let response = await fetch("http://localhost:3000/api/choozes/get-choozes");
    let responseFromServer = await response.json();

    return {
      props: {
        choozes: responseFromServer,
      },
    };
  } catch (e) {
    console.log("error ", e);
    return {
      props: {
        choozes: "",
      },
    };
  }
}

export default function Home(props) {
  const [choozes, setChoozes] = useState(props.choozes);
  choozes.map(chooze => {
    console.log(chooze);
  });
  return (
    <>
      <Head>
        <title>Chooze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/** NAVIGATION */}
        <section className="navigation">
          <a href="/" className="navigation-logo">
            <h1>Chooze</h1>
          </a>
          <FaPlus className="navigation-edit" />
        </section>

        {/** MAIN */}
        <section className="main">
          <header>
            <h2>Vos Choozes:</h2>
          </header>
          <section className="cards">
            {choozes ? (
              choozes?.map((chooze, index) => {
                return (
                  <article key={index} className="card">
                    <FaQuestion className="card__icon"/>
                    <h4 className="card__title">{chooze.question}</h4>
                    <FaTimes className="card__exit" />
                  </article>
                );
              })
            ) : (
              <h3>Vous n'avez pas encore de choozes</h3>
            )}
          </section>
        </section>
      </main>
    </>
  );
}
